services:
  - type: web
    name: django-chat-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "daphne chat_app.asgi:application --port $PORT --bind 0.0.0.0"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
