services:
  - type: web
    name: chat-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 -p 8000 chat_app.asgi:application"
    envVars:
      - key: PYTHONPATH
        value: "/opt/render/project/src/chat_app"
